### ISSUE TITLE
Create a new `Required` component

### ISSUE THREAD

**Issue by fabiankaegy** [10up/block-components#234]
It would be great to have a simple react component mark any component as required. It should work similar to the `<Optional>` component we already have in that you pass it a value that needs to exist in order for the condition to be met. 

If the condition is not met, but the block is in the document, the editor should be locked from saving anything using the core APIs. 

```js
const { lockPostSaving, unlockPostSaving } = useDispatch( 'core/editor' );

// we can then lock / unlock the editor using these functions here
lockPostSaving( 'title-empty-lock' );
unlockPostSaving( 'title-empty-lock' );
```

Removing the block should also unlock the editor. 

Additionally, it would be great to show the reason why the editor is locked in a notice when the user tries to save the post & also something in the `PrePublishCheck` to show all the required fields that are empty would be great. 
```[tasklist]
### Tasks
- [ ] Lock the editor when a block containing at least one `Required` component is rendered
- [ ] Unlock the editor when all `Required` components in the entire editor have their conditional met (Each item will handle it's own locked state)
- [ ] Unlock the editor when the block containing the required field gets removed.
```

I think we should be able to use the clean up function of a `useEffect` hook to handle the unlocking on removal for us.

```js
useEffect( () => {

    if (!condition) {
        // lock the editor
    } else {
        // unlock the editor
    }

    return () => {
        // unlock the editor
    }

}, [condition] )
```

**Comment by Sidsector9** [comment]
@fabiankaegy I'll pick this up

**Comment by Sidsector9** [comment]
@fabiankaegy I wanted to discuss this point:

> Unlock the editor when all Required components in the entire editor have their conditional met (Each item will handle it's own locked state)


I added 2 required fields:

```jsx
edit: ( { attributes, setAttributes } ) => {
	const blockProps = useBlockProps();
	const { fname, lname } = attributes;

	return (
		<div {...blockProps}>
			<Required value={ fname }>
				<TextControl
					label="First name"
					value={ fname }
					onChange={ ( val ) => setAttributes( { fname: val } ) }
				/>
			</Required>
			<Required value={ lname }>
				<TextControl
					label="Last name"
					value={ lname }
					onChange={ ( val ) => setAttributes( { lname: val } ) }
				/>
			</Required>
		</div>
	)
}
```

I found an issue with `Required` component maintaining its own state. When you fill in at least 1 field, then the post saving in unlocked. To solve this, I [created a custom data store](https://github.com/10up/block-components/pull/235/files#diff-bef88199100315e8df514da3b66e86661ff78f44e2f0cc089ccbf5e3ed7cbe38) that manages all the `Required` fields. 
Wondering if you have a better approach?

**Comment by Sidsector9** [comment]
Ah I think using unique identifiers for `lockPostSaving` and `unlockPostSaving` will do the job. We won't need the data store after all!
